export type DebugCompatibilityTier = "launch-critical" | "extended";

export type DebugCapability = {
  language: string;
  label: string;
  adapter: string;
  installHint: string;
  launchKinds: string[];
  frameworks: string[];
  samplePaths: string[];
  manifestPaths: string[];
  tier: DebugCompatibilityTier;
};

export const DEBUGGER_REQUIRED_FLOWS = [
  "adapter inference",
  "gutter breakpoint",
  "enable disable breakpoint",
  "conditional breakpoint",
  "logpoint",
  "captured value",
  "send breakpoint to assistant",
  "send value to assistant",
] as const;

export const DEBUGGER_COMPATIBILITY_MATRIX: DebugCapability[] = [
  {
    language: "javascript",
    label: "JavaScript / Node / browser",
    adapter: "js-debug",
    installHint: "Bundled in VS Code; Pointer can drive js-debug when the adapter is installed.",
    launchKinds: ["node", "browser", "test", "attach"],
    frameworks: [
      "node",
      "bun",
      "deno",
      "express",
      "nestjs",
      "react native",
      "jest",
      "playwright",
    ],
    samplePaths: ["server/index.js", "src/App.jsx", "next.config.js"],
    manifestPaths: ["package.json", "jest.config.js", "playwright.config.js"],
    tier: "launch-critical",
  },
  {
    language: "typescript",
    label: "TypeScript / Node / browser",
    adapter: "js-debug",
    installHint: "Use js-debug with source maps enabled.",
    launchKinds: ["node", "browser", "test", "attach"],
    frameworks: [
      "node",
      "vite",
      "next",
      "react",
      "vue",
      "nuxt",
      "angular",
      "svelte",
      "astro",
      "remix",
      "nestjs",
      "jest",
      "vitest",
      "playwright",
    ],
    samplePaths: ["src/App.tsx", "src/main.ts", "src/App.vue", "src/App.svelte"],
    manifestPaths: [
      "package.json",
      "vite.config.ts",
      "next.config.ts",
      "nuxt.config.ts",
      "angular.json",
      "vitest.config.ts",
    ],
    tier: "launch-critical",
  },
  {
    language: "python",
    label: "Python",
    adapter: "debugpy",
    installHint: "Install debugpy in the active Python environment.",
    launchKinds: ["script", "module", "pytest", "attach"],
    frameworks: ["django", "flask", "fastapi", "pytest", "celery", "jupyter"],
    samplePaths: ["app.py", "tests/test_app.py", "notebooks/debug_fixture.py"],
    manifestPaths: ["pyproject.toml", "requirements.txt", "manage.py", "pytest.ini"],
    tier: "launch-critical",
  },
  {
    language: "rust",
    label: "Rust",
    adapter: "CodeLLDB / lldb-dap",
    installHint: "Install CodeLLDB or ensure lldb-dap is on PATH.",
    launchKinds: ["cargo run", "cargo test", "attach"],
    frameworks: ["cargo", "tokio", "axum", "actix", "tauri"],
    samplePaths: ["src/main.rs", "src/lib.rs"],
    manifestPaths: ["Cargo.toml", "src-tauri/Cargo.toml"],
    tier: "launch-critical",
  },
  {
    language: "go",
    label: "Go",
    adapter: "dlv dap",
    installHint: "Install Delve (`go install github.com/go-delve/delve/cmd/dlv@latest`).",
    launchKinds: ["package", "test", "attach"],
    frameworks: ["go test", "go run", "gin", "echo", "fiber"],
    samplePaths: ["cmd/server/main.go", "internal/app/app_test.go"],
    manifestPaths: ["go.mod", "go.work"],
    tier: "launch-critical",
  },
  {
    language: "csharp",
    label: ".NET",
    adapter: "netcoredbg",
    installHint: "Install netcoredbg or use a compatible C# debug adapter.",
    launchKinds: ["project", "test", "attach"],
    frameworks: ["aspnet", "blazor", "xunit", "nunit", "mstest"],
    samplePaths: ["Program.cs", "Controllers/HealthController.cs"],
    manifestPaths: ["*.csproj", "*.sln"],
    tier: "launch-critical",
  },
  {
    language: "java",
    label: "Java",
    adapter: "java-debug",
    installHint: "Install the Java debug server and language support.",
    launchKinds: ["class", "test", "attach"],
    frameworks: ["maven", "gradle", "spring", "junit", "testng"],
    samplePaths: ["src/main/java/com/example/App.java"],
    manifestPaths: ["pom.xml", "build.gradle", "settings.gradle"],
    tier: "launch-critical",
  },
  {
    language: "php",
    label: "PHP",
    adapter: "xdebug",
    installHint: "Install Xdebug and configure a debug listener.",
    launchKinds: ["listen", "script", "test"],
    frameworks: ["laravel", "symfony", "wordpress", "phpunit", "pest"],
    samplePaths: ["app/Http/Controllers/HealthController.php", "tests/Feature/HealthTest.php"],
    manifestPaths: ["composer.json", "phpunit.xml"],
    tier: "launch-critical",
  },
  {
    language: "ruby",
    label: "Ruby",
    adapter: "rdbg",
    installHint: "Install the debug gem (`bundle add debug`).",
    launchKinds: ["script", "test", "rails"],
    frameworks: ["rails", "sinatra", "rspec", "minitest"],
    samplePaths: ["app/models/user.rb", "spec/models/user_spec.rb"],
    manifestPaths: ["Gemfile", "*.gemspec", ".rspec"],
    tier: "launch-critical",
  },
  {
    language: "c",
    label: "C",
    adapter: "lldb-dap / cpptools",
    installHint: "Install lldb-dap, CodeLLDB, or the C/C++ debug adapter for native debugging.",
    launchKinds: ["executable", "test binary", "attach"],
    frameworks: ["cmake", "make", "meson", "bazel", "check", "unity"],
    samplePaths: ["src/main.c", "include/app.h"],
    manifestPaths: ["CMakeLists.txt", "Makefile", "meson.build", "compile_commands.json"],
    tier: "launch-critical",
  },
  {
    language: "cpp",
    label: "C++",
    adapter: "lldb-dap / cpptools",
    installHint: "Install lldb-dap, CodeLLDB, or the C/C++ debug adapter for native debugging.",
    launchKinds: ["executable", "test binary", "attach"],
    frameworks: ["cmake", "make", "meson", "bazel", "gtest", "catch2"],
    samplePaths: ["src/main.cpp", "include/app.hpp"],
    manifestPaths: ["CMakeLists.txt", "Makefile", "meson.build", "compile_commands.json"],
    tier: "launch-critical",
  },
  {
    language: "objective-c",
    label: "Objective-C",
    adapter: "lldb-dap",
    installHint: "Install Xcode command line tools or lldb-dap.",
    launchKinds: ["app", "executable", "test"],
    frameworks: ["xcode", "cocoa", "uikit", "xctest"],
    samplePaths: ["AppDelegate.m", "ViewController.mm"],
    manifestPaths: ["*.xcodeproj", "*.xcworkspace"],
    tier: "launch-critical",
  },
  {
    language: "swift",
    label: "Swift",
    adapter: "lldb-dap",
    installHint: "Install Xcode command line tools or lldb-dap.",
    launchKinds: ["swift package", "app", "test"],
    frameworks: ["swiftpm", "xcode", "swiftui", "vapor", "xctest"],
    samplePaths: ["Sources/App/App.swift", "Tests/AppTests/AppTests.swift"],
    manifestPaths: ["Package.swift", "*.xcodeproj", "*.xcworkspace"],
    tier: "launch-critical",
  },
  {
    language: "kotlin",
    label: "Kotlin / JVM",
    adapter: "java-debug",
    installHint: "Install the Java debug server with Kotlin/JVM language support.",
    launchKinds: ["class", "gradle test", "app"],
    frameworks: ["gradle", "spring", "ktor", "android", "junit"],
    samplePaths: ["src/main/kotlin/App.kt", "app/src/main/java/com/example/MainActivity.kt"],
    manifestPaths: ["build.gradle.kts", "settings.gradle.kts"],
    tier: "launch-critical",
  },
  {
    language: "scala",
    label: "Scala / JVM",
    adapter: "java-debug",
    installHint: "Install the Java debug server and Scala language tooling.",
    launchKinds: ["class", "sbt run", "test"],
    frameworks: ["sbt", "akka", "play", "zio", "munit", "scalatest"],
    samplePaths: ["src/main/scala/App.scala"],
    manifestPaths: ["build.sbt"],
    tier: "launch-critical",
  },
  {
    language: "groovy",
    label: "Groovy / Gradle",
    adapter: "java-debug",
    installHint: "Install the Java debug server for Groovy or Gradle debugging.",
    launchKinds: ["script", "gradle task", "test"],
    frameworks: ["gradle", "spock", "grails"],
    samplePaths: ["src/main/groovy/App.groovy", "build.gradle"],
    manifestPaths: ["build.gradle", "settings.gradle"],
    tier: "extended",
  },
  {
    language: "clojure",
    label: "Clojure",
    adapter: "java-debug",
    installHint: "Install the Java debug server and Clojure tooling such as nREPL/cider-nrepl.",
    launchKinds: ["repl", "main", "test"],
    frameworks: ["deps.edn", "leiningen", "shadow-cljs"],
    samplePaths: ["src/example/core.clj", "src/example/core.cljs"],
    manifestPaths: ["deps.edn", "project.clj", "shadow-cljs.edn"],
    tier: "extended",
  },
  {
    language: "fsharp",
    label: "F#",
    adapter: "netcoredbg",
    installHint: "Install netcoredbg or a compatible .NET debug adapter.",
    launchKinds: ["project", "script", "test"],
    frameworks: ["dotnet", "fable", "expecto", "xunit"],
    samplePaths: ["Program.fs", "scripts/debug.fsx"],
    manifestPaths: ["*.fsproj"],
    tier: "extended",
  },
  {
    language: "dart",
    label: "Dart / Flutter",
    adapter: "dart-debug-adapter",
    installHint: "Install the Dart SDK or Flutter SDK.",
    launchKinds: ["dart", "flutter", "test"],
    frameworks: ["flutter", "dart test", "riverpod", "bloc"],
    samplePaths: ["lib/main.dart", "test/widget_test.dart"],
    manifestPaths: ["pubspec.yaml"],
    tier: "launch-critical",
  },
  {
    language: "shell",
    label: "Shell",
    adapter: "bashdb",
    installHint: "Install bashdb or a shell-compatible debug adapter.",
    launchKinds: ["script"],
    frameworks: ["bash", "zsh", "shunit2", "bats"],
    samplePaths: ["scripts/health.sh", "scripts/health.zsh"],
    manifestPaths: ["test.bats"],
    tier: "launch-critical",
  },
  {
    language: "powershell",
    label: "PowerShell",
    adapter: "PowerShell Editor Services",
    installHint: "Install PowerShell Editor Services.",
    launchKinds: ["script", "test"],
    frameworks: ["powershell", "pester"],
    samplePaths: ["scripts/Health.ps1"],
    manifestPaths: ["*.Tests.ps1"],
    tier: "launch-critical",
  },
  {
    language: "lua",
    label: "Lua",
    adapter: "local-lua-debugger",
    installHint: "Install a Lua debug adapter compatible with the project runtime.",
    launchKinds: ["script", "test"],
    frameworks: ["lua", "luarocks", "busted", "neovim"],
    samplePaths: ["lua/app.lua"],
    manifestPaths: ["*.rockspec"],
    tier: "extended",
  },
  {
    language: "perl",
    label: "Perl",
    adapter: "perl-debug-adapter",
    installHint: "Install a Perl debug adapter for the active Perl runtime.",
    launchKinds: ["script", "test"],
    frameworks: ["prove", "mojolicious", "dancer"],
    samplePaths: ["script/app.pl", "lib/App.pm"],
    manifestPaths: ["cpanfile"],
    tier: "extended",
  },
  {
    language: "r",
    label: "R",
    adapter: "R Debugger",
    installHint: "Install an R debug adapter for the active R installation.",
    launchKinds: ["script", "package test"],
    frameworks: ["testthat", "shiny", "renv"],
    samplePaths: ["R/app.R", "analysis/report.Rmd"],
    manifestPaths: ["renv.lock", "DESCRIPTION"],
    tier: "extended",
  },
  {
    language: "haskell",
    label: "Haskell",
    adapter: "haskell-debug-adapter",
    installHint: "Install a Haskell debug adapter compatible with GHC/HLS.",
    launchKinds: ["cabal run", "stack run", "test"],
    frameworks: ["cabal", "stack", "hpack", "hspec"],
    samplePaths: ["app/Main.hs", "src/Lib.lhs"],
    manifestPaths: ["*.cabal", "stack.yaml", "package.yaml"],
    tier: "extended",
  },
  {
    language: "elixir",
    label: "Elixir",
    adapter: "elixir-ls-debugger",
    installHint: "Install ElixirLS with debugger support.",
    launchKinds: ["mix run", "mix test"],
    frameworks: ["mix", "phoenix", "exunit", "liveview"],
    samplePaths: ["lib/app.ex", "test/app_test.exs"],
    manifestPaths: ["mix.exs"],
    tier: "extended",
  },
  {
    language: "erlang",
    label: "Erlang",
    adapter: "erlang-debugger",
    installHint: "Install an Erlang debug adapter for the active OTP release.",
    launchKinds: ["module", "test"],
    frameworks: ["rebar3", "otp", "common test", "eunit"],
    samplePaths: ["src/app.erl", "include/app.hrl"],
    manifestPaths: ["rebar.config"],
    tier: "extended",
  },
  {
    language: "julia",
    label: "Julia",
    adapter: "Julia VS Code Debug Adapter",
    installHint: "Install the Julia VS Code debug adapter for the active Julia environment.",
    launchKinds: ["script", "package test", "repl"],
    frameworks: ["pkg", "test", "pluto"],
    samplePaths: ["src/App.jl", "test/runtests.jl"],
    manifestPaths: ["Project.toml", "Manifest.toml"],
    tier: "extended",
  },
  {
    language: "zig",
    label: "Zig",
    adapter: "lldb-dap",
    installHint: "Install lldb-dap and build with debug symbols.",
    launchKinds: ["zig build run", "zig test", "executable"],
    frameworks: ["zig build", "zig test"],
    samplePaths: ["src/main.zig", "build.zig"],
    manifestPaths: ["build.zig", "build.zig.zon"],
    tier: "extended",
  },
  {
    language: "ocaml",
    label: "OCaml",
    adapter: "ocamlearlybird",
    installHint: "Install ocamlearlybird and build bytecode artifacts with debug information.",
    launchKinds: ["dune exec", "dune runtest"],
    frameworks: ["dune", "opam", "alcotest"],
    samplePaths: ["bin/main.ml", "lib/app.mli"],
    manifestPaths: ["dune-project", "*.opam"],
    tier: "extended",
  },
];

export const DEBUGGER_LAUNCH_CRITICAL_LANGUAGES = DEBUGGER_COMPATIBILITY_MATRIX
  .filter((cap) => cap.tier === "launch-critical")
  .map((cap) => cap.language);
