import type { editor } from "monaco-editor";
import type { ThemeRegistration } from "shiki";

export const POINTER_NOIR_ID = "pointer-noir";

export const pointerNoirTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "E8E8F2", background: "0A0A0C" },
    { token: "comment", foreground: "6B6B7B", fontStyle: "italic" },
    { token: "keyword", foreground: "FF7AB2", fontStyle: "italic" },
    { token: "keyword.control", foreground: "FF7AB2", fontStyle: "italic" },
    { token: "keyword.operator", foreground: "C7C7D8" },
    { token: "operator", foreground: "C7C7D8" },
    { token: "string", foreground: "FFD480" },
    { token: "string.escape", foreground: "FFA94D" },
    { token: "number", foreground: "FFB3CE" },
    { token: "boolean", foreground: "FFB3CE", fontStyle: "italic" },
    { token: "constant", foreground: "FFB3CE" },
    { token: "type", foreground: "8AD9FF" },
    { token: "type.identifier", foreground: "8AD9FF" },
    { token: "class", foreground: "8AD9FF" },
    { token: "interface", foreground: "8AD9FF" },
    { token: "enum", foreground: "8AD9FF" },
    { token: "function", foreground: "7CF0BD" },
    { token: "support.function", foreground: "7CF0BD" },
    { token: "variable", foreground: "E8E8F2" },
    { token: "variable.parameter", foreground: "D6BCFF" },
    { token: "variable.predefined", foreground: "D6BCFF" },
    { token: "property", foreground: "E8E8F2" },
    { token: "tag", foreground: "FF7AB2" },
    { token: "attribute.name", foreground: "D6BCFF" },
    { token: "attribute.value", foreground: "FFD480" },
    { token: "delimiter", foreground: "8C8CA0" },
    { token: "delimiter.bracket", foreground: "8C8CA0" },
    { token: "namespace", foreground: "8AD9FF" },
    { token: "regexp", foreground: "FFD480" },
    { token: "meta.embedded", foreground: "E8E8F2" },
  ],
  colors: {
    "editor.background": "#0A0A0C",
    "editor.foreground": "#E8E8F2",
    "editor.lineHighlightBackground": "#101014",
    "editor.lineHighlightBorder": "#10101400",
    "editorLineNumber.foreground": "#3A3A48",
    "editorLineNumber.activeForeground": "#A9A9BD",
    "editorCursor.foreground": "#FF2D7E",
    "editorIndentGuide.background": "#1A1A22",
    "editorIndentGuide.activeBackground": "#2A2A36",
    "editorWhitespace.foreground": "#1A1A22",
    "editor.selectionBackground": "#FF2D7E33",
    "editor.selectionHighlightBackground": "#FF2D7E1A",
    "editor.inactiveSelectionBackground": "#FF2D7E1A",
    "editor.wordHighlightBackground": "#FF2D7E1A",
    "editor.wordHighlightStrongBackground": "#FF2D7E26",
    "editorBracketMatch.background": "#FF2D7E22",
    "editorBracketMatch.border": "#FF2D7E66",
    "editorOverviewRuler.border": "#00000000",
    "editorGutter.background": "#0A0A0C",
    "editor.findMatchBackground": "#FFD48033",
    "editor.findMatchHighlightBackground": "#FFD48022",
    "editorWidget.background": "#101014",
    "editorWidget.border": "#26262F",
    "editorSuggestWidget.background": "#101014",
    "editorSuggestWidget.border": "#26262F",
    "editorSuggestWidget.foreground": "#E8E8F2",
    "editorSuggestWidget.highlightForeground": "#FF2D7E",
    "editorSuggestWidget.selectedBackground": "#1D1D26",
    "editorHoverWidget.background": "#101014",
    "editorHoverWidget.border": "#26262F",
    "scrollbarSlider.background": "#26262F88",
    "scrollbarSlider.hoverBackground": "#3A3A48AA",
    "scrollbarSlider.activeBackground": "#FF2D7E66",
    "diffEditor.insertedTextBackground": "#7CF0BD15",
    "diffEditor.removedTextBackground": "#FF6F9115",
    "minimap.background": "#0A0A0C",
  },
};

export const pointerNoirShikiTheme = {
  name: POINTER_NOIR_ID,
  displayName: "Pointer Noir",
  type: "dark",
  fg: "#E8E8F2",
  bg: "#0A0A0C",
  colors: pointerNoirTheme.colors,
  settings: [
    {
      settings: {
        foreground: "#E8E8F2",
        background: "#0A0A0C",
      },
    },
    {
      scope: [
        "comment",
        "punctuation.definition.comment",
        "string.comment",
      ],
      settings: { foreground: "#6B6B7B", fontStyle: "italic" },
    },
    {
      scope: [
        "keyword",
        "keyword.control",
        "keyword.operator.expression",
        "storage",
        "storage.type",
        "storage.modifier",
      ],
      settings: { foreground: "#FF7AB2", fontStyle: "italic" },
    },
    {
      scope: [
        "keyword.operator",
        "punctuation",
        "punctuation.separator",
        "punctuation.terminator",
        "meta.brace",
      ],
      settings: { foreground: "#8C8CA0" },
    },
    {
      scope: [
        "string",
        "string.quoted",
        "string.template",
        "constant.other.symbol",
        "markup.inline.raw",
      ],
      settings: { foreground: "#FFD480" },
    },
    {
      scope: [
        "constant.numeric",
        "constant.language",
        "constant.character",
        "support.constant",
        "variable.other.enummember",
      ],
      settings: { foreground: "#FFB3CE" },
    },
    {
      scope: [
        "entity.name.function",
        "meta.function-call",
        "support.function",
        "variable.function",
      ],
      settings: { foreground: "#7CF0BD" },
    },
    {
      scope: [
        "entity.name.type",
        "entity.name.class",
        "entity.name.struct",
        "entity.name.enum",
        "entity.name.interface",
        "support.type",
        "support.class",
      ],
      settings: { foreground: "#8AD9FF" },
    },
    {
      scope: [
        "variable.parameter",
        "variable.other.readwrite.alias",
        "meta.object-literal.key",
      ],
      settings: { foreground: "#D6BCFF" },
    },
    {
      scope: [
        "variable",
        "variable.other",
        "entity.name.variable",
        "support.variable",
        "support.variable.property",
        "variable.other.property",
        "meta.property-name",
      ],
      settings: { foreground: "#E8E8F2" },
    },
    {
      scope: [
        "entity.name.tag",
        "punctuation.definition.tag",
        "meta.tag",
      ],
      settings: { foreground: "#FF7AB2" },
    },
    {
      scope: [
        "entity.other.attribute-name",
        "entity.other.attribute-name.class",
        "entity.other.attribute-name.id",
      ],
      settings: { foreground: "#D6BCFF" },
    },
    {
      scope: [
        "markup.heading",
        "markup.heading entity.name",
        "entity.name.section",
      ],
      settings: { foreground: "#8AD9FF", fontStyle: "bold" },
    },
    {
      scope: ["markup.bold"],
      settings: { fontStyle: "bold" },
    },
    {
      scope: ["markup.italic"],
      settings: { fontStyle: "italic" },
    },
    {
      scope: ["markup.inserted"],
      settings: { foreground: "#7CF0BD" },
    },
    {
      scope: ["markup.deleted"],
      settings: { foreground: "#FF6F91" },
    },
    {
      scope: [
        "invalid",
        "invalid.illegal",
        "diagnostic.error",
      ],
      settings: { foreground: "#FF6F91" },
    },
  ],
} satisfies ThemeRegistration;
