import type { editor } from "monaco-editor";
import type { ThemeRegistration } from "shiki";

export const POINTER_THEME_IDS = [
  "pointer-noir",
  "pointer-gris",
  "pointer-blanc",
  "pointer-magnet",
  "pointer-alien",
  "pointer-pastelle",
  "pointer-paladin",
  "pointer-desert-sage",
  "pointer-salmon",
  "pointer-dark-photon",
  "pointer-harmonic-tide",
  "pointer-rocket",
  "pointer-meteor",
  "pointer-dark-cola",
  "pointer-vampire",
  "pointer-monkey-pro",
] as const;

export type AppThemeId = (typeof POINTER_THEME_IDS)[number];
export type ThemeType = "dark" | "light";

type CssVarName = `--pn-${string}`;

type BaseTokenPalette = {
  bg: string;
  fg: string;
  comment: string;
  keyword: string;
  operator: string;
  string: string;
  escape: string;
  number: string;
  constant: string;
  type: string;
  function: string;
  parameter: string;
  property: string;
  tag: string;
  attribute: string;
  delimiter: string;
  invalid: string;
  inserted: string;
  deleted: string;
  selection: string;
  inactiveSelection: string;
  lineHighlight: string;
  lineNumber: string;
  activeLineNumber: string;
  cursor: string;
  indent: string;
  activeIndent: string;
  whitespace: string;
  widgetBg: string;
  widgetBorder: string;
  suggestSelected: string;
  ghost: string;
  ghostBg: string;
  find: string;
  findHighlight: string;
};

type SemanticTokenPalette = {
  variable: string;
  builtin: string;
  decorator: string;
  macro: string;
  namespace: string;
  module: string;
  label: string;
  selector: string;
  configKey: string;
  configValue: string;
  configSection: string;
  markupHeading: string;
  markupBold: string;
  markupLink: string;
  markupQuote: string;
  markupCode: string;
  regex: string;
  tagBracket: string;
  attributeValue: string;
};

type TokenPalette = BaseTokenPalette & Partial<SemanticTokenPalette>;
type ResolvedTokenPalette = BaseTokenPalette & SemanticTokenPalette;

export type PointerTheme = {
  id: AppThemeId;
  label: string;
  menuLabel: string;
  type: ThemeType;
  css: Record<CssVarName, string>;
  monaco: editor.IStandaloneThemeData;
  shiki: ThemeRegistration;
};

function h(value: string): string {
  return value.startsWith("#") ? value : `#${value}`;
}

function bare(value: string): string {
  return h(value).slice(1);
}

function alpha(hex: string, aa: string): string {
  return `${h(hex)}${aa}`;
}

function resolveTokenPalette(t: TokenPalette): ResolvedTokenPalette {
  const operator = pickDistinctColor(t.operator, [t.keyword, t.function, t.tag], t.fg);
  const delimiter = pickDistinctColor(t.delimiter, [operator, t.keyword, t.tag], t.fg);
  const type = pickDistinctColor(t.type, [t.function, t.number, t.tag, t.keyword], t.fg);
  const parameter = pickDistinctColor(t.parameter, [t.number, type, t.function, t.keyword], t.fg);
  const variable = t.variable ?? parameter;
  const property = pickDistinctColor(t.property, [t.number, t.function, t.attribute, type], t.fg);
  const attribute = pickDistinctColor(t.attribute, [t.number, parameter, type, t.function, t.keyword], t.fg);

  return {
    ...t,
    operator,
    delimiter,
    type,
    parameter,
    property,
    attribute,
    variable,
    builtin: t.constant,
    decorator: attribute,
    macro: t.keyword,
    namespace: type,
    module: t.string,
    label: t.function,
    selector: t.tag,
    configKey: attribute,
    configValue: t.string,
    configSection: type,
    markupHeading: type,
    markupBold: t.fg,
    markupLink: t.function,
    markupQuote: t.comment,
    markupCode: t.string,
    regex: t.escape,
    tagBracket: t.tagBracket ?? pickDistinctColor(t.delimiter, [operator, t.keyword, t.tag], t.fg),
    attributeValue: t.string,
  };
}

function pickDistinctColor(preferred: string, fallbacks: string[], against: string): string {
  const candidates = [preferred, ...fallbacks];
  return candidates.find((candidate) => colorDistance(candidate, against) >= 28) ?? preferred;
}

function colorDistance(a: string, b: string): number {
  const rgbA = hexToRgbChannels(a);
  const rgbB = hexToRgbChannels(b);
  if (!rgbA || !rgbB) return a.toLowerCase() === b.toLowerCase() ? 0 : 255;
  return Math.hypot(rgbA[0] - rgbB[0], rgbA[1] - rgbB[1], rgbA[2] - rgbB[2]);
}

function hexToRgbChannels(value: string): [number, number, number] | null {
  const raw = value.trim().replace(/^#/, "");
  const hex =
    raw.length === 3
      ? raw
          .split("")
          .map((ch) => `${ch}${ch}`)
          .join("")
      : raw.length >= 6
        ? raw.slice(0, 6)
        : null;
  if (!hex || !/^[0-9a-f]{6}$/i.test(hex)) return null;
  return [0, 2, 4].map((index) => parseInt(hex.slice(index, index + 2), 16)) as [
    number,
    number,
    number,
  ];
}

function tokenCssVariables(t: ResolvedTokenPalette): Record<CssVarName, string> {
  return {
    "--pn-code-bg": t.bg,
    "--pn-code-fg": t.fg,
    "--pn-code-comment": t.comment,
    "--pn-code-keyword": t.keyword,
    "--pn-code-operator": t.operator,
    "--pn-code-string": t.string,
    "--pn-code-escape": t.escape,
    "--pn-code-number": t.number,
    "--pn-code-constant": t.constant,
    "--pn-code-variable": t.variable,
    "--pn-code-builtin": t.builtin,
    "--pn-code-type": t.type,
    "--pn-code-function": t.function,
    "--pn-code-parameter": t.parameter,
    "--pn-code-property": t.property,
    "--pn-code-decorator": t.decorator,
    "--pn-code-macro": t.macro,
    "--pn-code-namespace": t.namespace,
    "--pn-code-module": t.module,
    "--pn-code-label": t.label,
    "--pn-code-tag": t.tag,
    "--pn-code-tag-bracket": t.tagBracket,
    "--pn-code-attribute": t.attribute,
    "--pn-code-attribute-value": t.attributeValue,
    "--pn-code-selector": t.selector,
    "--pn-code-config-key": t.configKey,
    "--pn-code-config-value": t.configValue,
    "--pn-code-config-section": t.configSection,
    "--pn-code-delimiter": t.delimiter,
    "--pn-code-markup-heading": t.markupHeading,
    "--pn-code-markup-bold": t.markupBold,
    "--pn-code-markup-link": t.markupLink,
    "--pn-code-markup-quote": t.markupQuote,
    "--pn-code-markup-code": t.markupCode,
    "--pn-code-regex": t.regex,
    "--pn-code-invalid": t.invalid,
    "--pn-code-inserted": t.inserted,
    "--pn-code-deleted": t.deleted,
  };
}

function hexToRgbTriplet(value: string): string | null {
  const raw = value.trim().replace(/^#/, "");
  const hex =
    raw.length === 3
      ? raw
          .split("")
          .map((ch) => `${ch}${ch}`)
          .join("")
      : raw.length === 6 || raw.length === 8
        ? raw.slice(0, 6)
        : null;
  if (!hex || !/^[0-9a-f]{6}$/i.test(hex)) return null;
  const channels = [0, 2, 4].map((index) => parseInt(hex.slice(index, index + 2), 16));
  return channels.join(" ");
}

function createMonacoTheme(type: ThemeType, t: ResolvedTokenPalette): editor.IStandaloneThemeData {
  return {
    base: type === "light" ? "vs" : "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: bare(t.fg), background: bare(t.bg) },
      { token: "comment", foreground: bare(t.comment), fontStyle: "italic" },
      { token: "comment.doc", foreground: bare(t.markupQuote), fontStyle: "italic" },
      { token: "keyword", foreground: bare(t.keyword), fontStyle: "bold" },
      { token: "keyword.control", foreground: bare(t.keyword), fontStyle: "bold" },
      { token: "keyword.operator", foreground: bare(t.operator) },
      { token: "operator", foreground: bare(t.operator) },
      { token: "string", foreground: bare(t.string) },
      { token: "string.key", foreground: bare(t.configKey) },
      { token: "string.value", foreground: bare(t.configValue) },
      { token: "string.escape", foreground: bare(t.escape) },
      { token: "string.regexp", foreground: bare(t.regex) },
      { token: "number", foreground: bare(t.number) },
      { token: "number.hex", foreground: bare(t.number) },
      { token: "boolean", foreground: bare(t.constant) },
      { token: "constant", foreground: bare(t.constant) },
      { token: "constant.language", foreground: bare(t.constant), fontStyle: "bold" },
      { token: "constant.character", foreground: bare(t.constant) },
      { token: "type", foreground: bare(t.type), fontStyle: "bold" },
      { token: "type.identifier", foreground: bare(t.type), fontStyle: "bold" },
      { token: "class", foreground: bare(t.type), fontStyle: "bold" },
      { token: "interface", foreground: bare(t.type), fontStyle: "bold" },
      { token: "enum", foreground: bare(t.type), fontStyle: "bold" },
      { token: "struct", foreground: bare(t.type), fontStyle: "bold" },
      { token: "function", foreground: bare(t.function), fontStyle: "bold" },
      { token: "support.function", foreground: bare(t.function) },
      { token: "method", foreground: bare(t.function) },
      { token: "identifier", foreground: bare(t.variable) },
      { token: "variable", foreground: bare(t.variable) },
      { token: "variable.parameter", foreground: bare(t.parameter) },
      { token: "variable.predefined", foreground: bare(t.builtin), fontStyle: "bold" },
      { token: "property", foreground: bare(t.property) },
      { token: "property.name", foreground: bare(t.property) },
      { token: "namespace", foreground: bare(t.namespace) },
      { token: "module", foreground: bare(t.module) },
      { token: "label", foreground: bare(t.label) },
      { token: "annotation", foreground: bare(t.decorator), fontStyle: "bold" },
      { token: "decorator", foreground: bare(t.decorator), fontStyle: "bold" },
      { token: "macro", foreground: bare(t.macro), fontStyle: "bold" },
      { token: "selector", foreground: bare(t.selector), fontStyle: "bold" },
      { token: "tag", foreground: bare(t.tag), fontStyle: "bold" },
      { token: "attribute.name", foreground: bare(t.attribute), fontStyle: "bold" },
      { token: "attribute.value", foreground: bare(t.attributeValue) },
      { token: "key", foreground: bare(t.configKey), fontStyle: "bold" },
      { token: "key.identifier", foreground: bare(t.configKey), fontStyle: "bold" },
      { token: "section", foreground: bare(t.configSection), fontStyle: "bold" },
      { token: "delimiter", foreground: bare(t.delimiter) },
      { token: "delimiter.bracket", foreground: bare(t.delimiter) },
      { token: "delimiter.html", foreground: bare(t.tagBracket) },
      { token: "delimiter.xml", foreground: bare(t.tagBracket) },
      { token: "delimiter.angle", foreground: bare(t.tagBracket) },
      { token: "regexp", foreground: bare(t.regex) },
      { token: "strong", foreground: bare(t.markupBold), fontStyle: "bold" },
      { token: "emphasis", foreground: bare(t.markupBold), fontStyle: "italic" },
      { token: "heading", foreground: bare(t.markupHeading), fontStyle: "bold" },
      { token: "link", foreground: bare(t.markupLink), fontStyle: "underline" },
      { token: "quote", foreground: bare(t.markupQuote), fontStyle: "italic" },
      { token: "code", foreground: bare(t.markupCode) },
      { token: "meta.embedded", foreground: bare(t.fg) },
      { token: "invalid", foreground: bare(t.invalid) },
    ],
    colors: {
      "editor.background": h(t.bg),
      "editor.foreground": h(t.fg),
      "editor.lineHighlightBackground": h(t.lineHighlight),
      "editor.lineHighlightBorder": alpha(t.lineHighlight, "00"),
      "editorLineNumber.foreground": h(t.lineNumber),
      "editorLineNumber.activeForeground": h(t.activeLineNumber),
      "editorCursor.foreground": h(t.cursor),
      "editorIndentGuide.background": alpha(t.indent, "44"),
      "editorIndentGuide.activeBackground": alpha(t.activeIndent, "78"),
      "editorIndentGuide.background1": alpha(t.indent, "44"),
      "editorIndentGuide.activeBackground1": alpha(t.activeIndent, "78"),
      "editorBracketPairGuide.background1": alpha(t.indent, "26"),
      "editorBracketPairGuide.background2": alpha(t.indent, "26"),
      "editorBracketPairGuide.background3": alpha(t.indent, "26"),
      "editorBracketPairGuide.background4": alpha(t.indent, "26"),
      "editorBracketPairGuide.background5": alpha(t.indent, "26"),
      "editorBracketPairGuide.background6": alpha(t.indent, "26"),
      "editorBracketPairGuide.activeBackground1": alpha(t.activeIndent, "66"),
      "editorBracketPairGuide.activeBackground2": alpha(t.activeIndent, "66"),
      "editorBracketPairGuide.activeBackground3": alpha(t.activeIndent, "66"),
      "editorBracketPairGuide.activeBackground4": alpha(t.activeIndent, "66"),
      "editorBracketPairGuide.activeBackground5": alpha(t.activeIndent, "66"),
      "editorBracketPairGuide.activeBackground6": alpha(t.activeIndent, "66"),
      "editorWhitespace.foreground": h(t.whitespace),
      "editorRuler.foreground": alpha(t.indent, "55"),
      "editor.selectionBackground": h(t.selection),
      "editor.selectionHighlightBackground": h(t.inactiveSelection),
      "editor.inactiveSelectionBackground": h(t.inactiveSelection),
      "editor.wordHighlightBackground": h(t.inactiveSelection),
      "editor.wordHighlightStrongBackground": h(t.selection),
      "editorGhostText.foreground": h(t.ghost),
      "editorGhostText.background": h(t.ghostBg),
      "editorGhostText.border": alpha(t.cursor, "55"),
      "editorBracketMatch.background": h(t.inactiveSelection),
      "editorBracketMatch.border": alpha(t.cursor, "66"),
      "editorOverviewRuler.border": "#00000000",
      "editorGutter.background": h(t.bg),
      "editor.findMatchBackground": h(t.find),
      "editor.findMatchHighlightBackground": h(t.findHighlight),
      "editorWidget.background": h(t.widgetBg),
      "editorWidget.border": h(t.widgetBorder),
      "editorSuggestWidget.background": h(t.widgetBg),
      "editorSuggestWidget.border": h(t.widgetBorder),
      "editorSuggestWidget.foreground": h(t.fg),
      "editorSuggestWidget.highlightForeground": h(t.cursor),
      "editorSuggestWidget.selectedBackground": h(t.suggestSelected),
      "editorHoverWidget.background": h(t.widgetBg),
      "editorHoverWidget.border": h(t.widgetBorder),
      "scrollbarSlider.background": alpha(t.widgetBorder, "88"),
      "scrollbarSlider.hoverBackground": alpha(t.activeIndent, "AA"),
      "scrollbarSlider.activeBackground": alpha(t.cursor, "66"),
      "diffEditor.insertedTextBackground": alpha(t.inserted, "18"),
      "diffEditor.removedTextBackground": alpha(t.deleted, "18"),
      "minimap.background": h(t.bg),
    },
  };
}

function createShikiTheme(
  id: AppThemeId,
  label: string,
  type: ThemeType,
  t: ResolvedTokenPalette,
  monaco: editor.IStandaloneThemeData,
): ThemeRegistration {
  return {
    name: id,
    displayName: label,
    type,
    fg: h(t.fg),
    bg: h(t.bg),
    colors: monaco.colors,
    settings: [
      { settings: { foreground: h(t.fg), background: h(t.bg) } },
      {
        scope: ["comment", "punctuation.definition.comment", "string.comment"],
        settings: { foreground: h(t.comment), fontStyle: "italic" },
      },
      {
        scope: [
          "keyword",
          "keyword.control",
          "keyword.operator.expression",
          "keyword.operator.logical",
          "keyword.other",
          "storage",
          "storage.type",
          "storage.modifier",
          "storage.type.class",
          "storage.type.function",
          "storage.type.interface",
          "storage.type.struct",
          "storage.type.enum",
          "storage.type.trait",
        ],
        settings: { foreground: h(t.keyword), fontStyle: "bold" },
      },
      {
        scope: [
          "keyword.operator",
          "punctuation",
          "punctuation.separator",
          "punctuation.terminator",
          "meta.brace",
        ],
        settings: { foreground: h(t.delimiter) },
      },
      {
        scope: [
          "string",
          "string.quoted",
          "string.template",
          "string.unquoted",
          "string.other.link",
          "constant.other.symbol",
          "constant.other.color",
          "markup.inline.raw",
        ],
        settings: { foreground: h(t.string) },
      },
      {
        scope: [
          "string.regexp",
          "string.regexp.js",
          "string.regexp.ts",
          "constant.other.character-class.regexp",
        ],
        settings: { foreground: h(t.regex) },
      },
      {
        scope: [
          "constant.numeric",
          "constant.language",
          "constant.character",
          "support.constant",
          "variable.other.enummember",
        ],
        settings: { foreground: h(t.constant) },
      },
      {
        scope: [
          "entity.name.function",
          "meta.function-call",
          "meta.function-call entity.name.function",
          "support.function",
          "variable.function",
          "entity.name.function.method",
          "entity.name.function.member",
        ],
        settings: { foreground: h(t.function), fontStyle: "bold" },
      },
      {
        scope: [
          "entity.name.type",
          "entity.name.class",
          "entity.name.struct",
          "entity.name.enum",
          "entity.name.interface",
          "entity.name.trait",
          "entity.name.type.module",
          "entity.name.type.namespace",
          "support.type",
          "support.class",
          "support.type.primitive",
        ],
        settings: { foreground: h(t.type), fontStyle: "bold" },
      },
      {
        scope: [
          "entity.name.namespace",
          "entity.name.scope-resolution",
          "support.other.namespace",
          "entity.name.package",
        ],
        settings: { foreground: h(t.namespace) },
      },
      {
        scope: [
          "entity.name.module",
          "support.module",
          "support.other.module",
          "string.unquoted.import",
        ],
        settings: { foreground: h(t.module) },
      },
      {
        scope: [
          "meta.decorator",
          "meta.annotation",
          "entity.name.function.decorator",
          "storage.type.annotation",
          "storage.type.annotation.java",
          "punctuation.definition.annotation",
        ],
        settings: { foreground: h(t.decorator), fontStyle: "bold" },
      },
      {
        scope: [
          "entity.name.function.macro",
          "support.function.macro",
          "meta.preprocessor",
          "keyword.control.directive",
          "keyword.other.directive",
        ],
        settings: { foreground: h(t.macro), fontStyle: "bold" },
      },
      {
        scope: [
          "variable.parameter",
          "variable.other.readwrite.alias",
          "meta.object-literal.key",
        ],
        settings: { foreground: h(t.parameter) },
      },
      {
        scope: [
          "variable",
          "variable.other",
          "entity.name.variable",
          "support.variable",
          "support.variable.property",
          "variable.other.property",
          "variable.other.property.js.jsx",
          "variable.other.property.tsx",
          "meta.property-name",
        ],
        settings: { foreground: h(t.property) },
      },
      {
        scope: [
          "entity.name.tag",
          "entity.name.tag.html",
          "entity.name.tag.xml",
          "entity.name.tag.jsx",
          "entity.name.tag.tsx",
          "entity.name.tag.js.jsx",
          "support.class.component",
          "support.class.component.js.jsx",
          "support.class.component.tsx",
        ],
        settings: { foreground: h(t.tag), fontStyle: "bold" },
      },
      {
        scope: [
          "punctuation.definition.tag",
          "punctuation.definition.tag.begin",
          "punctuation.definition.tag.end",
          "punctuation.definition.tag.xml",
          "punctuation.definition.tag.html",
          "punctuation.definition.tag.jsx",
          "punctuation.definition.tag.tsx",
          "punctuation.definition.tag.begin.js.jsx",
          "punctuation.definition.tag.end.js.jsx",
          "punctuation.definition.tag.begin.tsx",
          "punctuation.definition.tag.end.tsx",
        ],
        settings: { foreground: h(t.tagBracket) },
      },
      {
        scope: [
          "entity.other.attribute-name",
          "entity.other.attribute-name.class",
          "entity.other.attribute-name.id",
          "entity.other.attribute-name.html",
          "entity.other.attribute-name.xml",
          "entity.other.attribute-name.jsx",
          "entity.other.attribute-name.tsx",
          "entity.other.attribute-name.js.jsx",
          "meta.attribute",
        ],
        settings: { foreground: h(t.attribute), fontStyle: "bold" },
      },
      {
        scope: [
          "meta.tag string.quoted",
          "meta.tag string.unquoted",
          "meta.attribute-with-value string",
          "string.quoted.double.html",
          "string.quoted.single.html",
          "string.quoted.double.xml",
          "string.quoted.single.xml",
          "meta.tag string.quoted.double.js.jsx",
          "meta.tag string.quoted.single.js.jsx",
          "meta.tag string.template.js.jsx",
        ],
        settings: { foreground: h(t.attributeValue) },
      },
      {
        scope: [
          "meta.tag punctuation.definition.string.begin.js.jsx",
          "meta.tag punctuation.definition.string.end.js.jsx",
          "meta.tag punctuation.definition.string.begin.tsx",
          "meta.tag punctuation.definition.string.end.tsx",
        ],
        settings: { foreground: h(t.attributeValue) },
      },
      {
        scope: [
          "punctuation.section.embedded.begin.js.jsx",
          "punctuation.section.embedded.end.js.jsx",
          "punctuation.section.embedded.begin.tsx",
          "punctuation.section.embedded.end.tsx",
          "punctuation.definition.template-expression.begin.js.jsx",
          "punctuation.definition.template-expression.end.js.jsx",
          "punctuation.definition.template-expression.begin.tsx",
          "punctuation.definition.template-expression.end.tsx",
        ],
        settings: { foreground: h(t.operator) },
      },
      {
        scope: [
          "meta.jsx.children.js.jsx",
          "meta.jsx.children.tsx",
          "meta.embedded.expression.js.jsx",
          "meta.embedded.expression.tsx",
        ],
        settings: { foreground: h(t.variable) },
      },
      {
        scope: [
          "support.type.property-name",
          "support.type.property-name.json",
          "support.type.property-name.css",
          "support.type.property-name.scss",
          "constant.other.object.key",
          "meta.mapping.key",
          "meta.mapping.key.yaml",
          "entity.name.tag.yaml",
          "variable.other.key.yaml",
          "constant.other.key.toml",
          "keyword.other.definition.ini",
          "entity.other.attribute-name.toml",
        ],
        settings: { foreground: h(t.configKey), fontStyle: "bold" },
      },
      {
        scope: [
          "entity.name.section",
          "entity.name.section.group-title.ini",
          "entity.name.section.toml",
          "punctuation.definition.section.ini",
          "punctuation.definition.table.toml",
        ],
        settings: { foreground: h(t.configSection), fontStyle: "bold" },
      },
      {
        scope: [
          "meta.mapping.value",
          "meta.mapping.value.yaml",
          "constant.other.boolean.yaml",
          "constant.language.yaml",
          "constant.language.toml",
          "constant.other.time.datetime.offset.toml",
        ],
        settings: { foreground: h(t.configValue) },
      },
      {
        scope: [
          "entity.other.attribute-name.class.css",
          "entity.other.attribute-name.id.css",
          "entity.name.tag.css",
          "entity.other.attribute-name.pseudo-class.css",
          "entity.other.attribute-name.pseudo-element.css",
          "meta.selector",
          "meta.selector.css",
          "meta.selector.scss",
        ],
        settings: { foreground: h(t.selector), fontStyle: "bold" },
      },
      {
        scope: ["markup.heading", "markup.heading entity.name", "entity.name.section"],
        settings: { foreground: h(t.markupHeading), fontStyle: "bold" },
      },
      {
        scope: ["markup.bold", "markup.bold string", "markup.strong"],
        settings: { foreground: h(t.markupBold), fontStyle: "bold" },
      },
      { scope: ["markup.italic"], settings: { fontStyle: "italic" } },
      {
        scope: ["markup.underline.link", "markup.link", "string.other.link"],
        settings: { foreground: h(t.markupLink), fontStyle: "underline" },
      },
      {
        scope: ["markup.quote", "markup.quote punctuation.definition.blockquote"],
        settings: { foreground: h(t.markupQuote), fontStyle: "italic" },
      },
      {
        scope: ["markup.raw", "markup.fenced_code", "markup.inline.raw"],
        settings: { foreground: h(t.markupCode) },
      },
      { scope: ["markup.inserted"], settings: { foreground: h(t.inserted) } },
      { scope: ["markup.deleted"], settings: { foreground: h(t.deleted) } },
      {
        scope: ["invalid", "invalid.illegal", "diagnostic.error"],
        settings: { foreground: h(t.invalid) },
      },
    ],
  };
}

function createTheme(input: {
  id: AppThemeId;
  label: string;
  menuLabel?: string;
  type: ThemeType;
  css: Record<CssVarName, string>;
  tokens: TokenPalette;
}): PointerTheme {
  const tokens = resolveTokenPalette(input.tokens);
  const monaco = createMonacoTheme(input.type, tokens);
  return {
    id: input.id,
    label: input.label,
    menuLabel: input.menuLabel ?? input.label,
    type: input.type,
    css: {
      ...input.css,
      ...tokenCssVariables(tokens),
    },
    monaco,
    shiki: createShikiTheme(input.id, input.label, input.type, tokens, monaco),
  };
}

const pointerNoirTokens: TokenPalette = {
  bg: "#08070B",
  fg: "#F2EDF5",
  comment: "#7E7480",
  keyword: "#FF5A9F",
  operator: "#CFC7D4",
  string: "#FFD37A",
  escape: "#FF9B62",
  number: "#FF9BC4",
  constant: "#FF9BC4",
  type: "#78D8FF",
  function: "#7CE8B7",
  parameter: "#DDBBFF",
  property: "#F2EDF5",
  tag: "#FF5A9F",
  attribute: "#DDBBFF",
  delimiter: "#938899",
  invalid: "#FF5C86",
  inserted: "#7CE8B7",
  deleted: "#FF5C86",
  selection: "#FF2D7E36",
  inactiveSelection: "#FF2D7E1B",
  lineHighlight: "#111015",
  lineNumber: "#6D3B55",
  activeLineNumber: "#FF9BC4",
  cursor: "#FF3D8D",
  indent: "#241821",
  activeIndent: "#4B263A",
  whitespace: "#241821",
  widgetBg: "#111015",
  widgetBorder: "#4A253A",
  suggestSelected: "#211620",
  ghost: "#A79CAD",
  ghostBg: "#FF2D7E12",
  find: "#FFD37A36",
  findHighlight: "#FFD37A22",
};

const pointerGrisTokens: TokenPalette = {
  bg: "#302E33",
  fg: "#F2EEF3",
  comment: "#9B9099",
  keyword: "#FF6EA8",
  operator: "#D7D0D8",
  string: "#FFD27A",
  escape: "#FF9E6E",
  number: "#F6A3C7",
  constant: "#F6A3C7",
  type: "#8CDCF6",
  function: "#92E4B6",
  parameter: "#DDBDFF",
  property: "#F2EEF3",
  tag: "#FF6EA8",
  attribute: "#DDBDFF",
  delimiter: "#B4A9B2",
  invalid: "#FF6B8B",
  inserted: "#92E4B6",
  deleted: "#FF6B8B",
  selection: "#FF6EA838",
  inactiveSelection: "#FF6EA81C",
  lineHighlight: "#39363C",
  lineNumber: "#B47E99",
  activeLineNumber: "#FF9CC6",
  cursor: "#FF6EA8",
  indent: "#4C4650",
  activeIndent: "#685765",
  whitespace: "#4C4650",
  widgetBg: "#38353B",
  widgetBorder: "#6E5868",
  suggestSelected: "#443C46",
  ghost: "#B9ADB7",
  ghostBg: "#FF6EA814",
  find: "#FFD27A3A",
  findHighlight: "#FFD27A24",
};

const pointerBlancTokens: TokenPalette = {
  bg: "#FAF7FA",
  fg: "#211A20",
  comment: "#81707D",
  keyword: "#D62D76",
  operator: "#5F515B",
  string: "#8A5A00",
  escape: "#B45B10",
  number: "#A82861",
  constant: "#A82861",
  type: "#0B6F8F",
  function: "#19714A",
  parameter: "#7448B8",
  property: "#211A20",
  tag: "#D62D76",
  attribute: "#7448B8",
  delimiter: "#8F818B",
  invalid: "#C52845",
  inserted: "#16794E",
  deleted: "#C52845",
  selection: "#D92A6E30",
  inactiveSelection: "#D92A6E16",
  lineHighlight: "#F1ECF1",
  lineNumber: "#B19CA9",
  activeLineNumber: "#C82067",
  cursor: "#D92A6E",
  indent: "#E7DDE5",
  activeIndent: "#D6C5D0",
  whitespace: "#E7DDE5",
  widgetBg: "#FFFCFE",
  widgetBorder: "#D9C8D3",
  suggestSelected: "#F1E7EE",
  ghost: "#80717D",
  ghostBg: "#D92A6E10",
  find: "#C68A0030",
  findHighlight: "#C68A001C",
};

const pointerMagnetTokens: TokenPalette = {
  bg: "#2F3234",
  fg: "#E0FBFC",
  comment: "#899295",
  keyword: "#E76F51",
  operator: "#F4A261",
  string: "#E9C46A",
  escape: "#F4A261",
  number: "#2A9D8F",
  constant: "#2A9D8F",
  type: "#A8B0B2",
  function: "#E9C46A",
  parameter: "#F4A261",
  property: "#E0FBFC",
  tag: "#E76F51",
  attribute: "#2A9D8F",
  delimiter: "#A8B0B2",
  invalid: "#E76F51",
  inserted: "#2A9D8F",
  deleted: "#E76F51",
  selection: "#3F4446",
  inactiveSelection: "#3F444688",
  lineHighlight: "#373B3D",
  lineNumber: "#7F898C",
  activeLineNumber: "#E9C46A",
  cursor: "#E9C46A",
  indent: "#44494B",
  activeIndent: "#5A6264",
  whitespace: "#44494B",
  widgetBg: "#363A3C",
  widgetBorder: "#596164",
  suggestSelected: "#44494B",
  ghost: "#AAB5B7",
  ghostBg: "#E9C46A14",
  find: "#E9C46A3A",
  findHighlight: "#E9C46A24",
};

const pointerAlienTokens: TokenPalette = {
  bg: "#000000",
  fg: "#E0FBFC",
  comment: "#5B7780",
  keyword: "#E76F51",
  operator: "#F4A261",
  string: "#E9C46A",
  escape: "#F4A261",
  number: "#2A9D8F",
  constant: "#2A9D8F",
  type: "#A7F3F4",
  function: "#F4A261",
  parameter: "#E9C46A",
  property: "#E0FBFC",
  tag: "#E76F51",
  attribute: "#2A9D8F",
  delimiter: "#88A8AD",
  invalid: "#E76F51",
  inserted: "#2A9D8F",
  deleted: "#E76F51",
  selection: "#2A9D8F38",
  inactiveSelection: "#26465388",
  lineHighlight: "#060909",
  lineNumber: "#56727A",
  activeLineNumber: "#E9C46A",
  cursor: "#E0FBFC",
  indent: "#13262C",
  activeIndent: "#264653",
  whitespace: "#13262C",
  widgetBg: "#050707",
  widgetBorder: "#264653",
  suggestSelected: "#102A2E",
  ghost: "#7FA1A6",
  ghostBg: "#2A9D8F14",
  find: "#E9C46A3A",
  findHighlight: "#F4A26124",
  tagBracket: "#F4A261",
  attributeValue: "#E9C46A",
};

const pointerPastelleTokens: TokenPalette = {
  bg: "#ECE3C4",
  fg: "#332A35",
  comment: "#7D7182",
  keyword: "#A7424B",
  operator: "#996A2F",
  string: "#765A35",
  escape: "#A7424B",
  number: "#2F7278",
  constant: "#5F5573",
  type: "#5F5573",
  function: "#996A2F",
  parameter: "#7A6241",
  property: "#332A35",
  tag: "#A7424B",
  attribute: "#4E7477",
  delimiter: "#7C7466",
  invalid: "#B33E48",
  inserted: "#2F7278",
  deleted: "#A7424B",
  selection: "#EA8A8A55",
  inactiveSelection: "#739A9E33",
  lineHighlight: "#F4EBCF",
  lineNumber: "#8E7F73",
  activeLineNumber: "#877394",
  cursor: "#877394",
  indent: "#D7C8AB",
  activeIndent: "#CDBBA0",
  whitespace: "#D7C8AB",
  widgetBg: "#F6EED6",
  widgetBorder: "#CDBBA0",
  suggestSelected: "#E4D4B8",
  ghost: "#80736D",
  ghostBg: "#739A9E22",
  find: "#EA8A8A55",
  findHighlight: "#739A9E30",
  decorator: "#877394",
  macro: "#A7424B",
  namespace: "#5F5573",
  module: "#765A35",
  label: "#996A2F",
  selector: "#4E7477",
  configKey: "#4E7477",
  configValue: "#765A35",
  configSection: "#5F5573",
  markupHeading: "#5F5573",
  markupLink: "#996A2F",
  markupQuote: "#7D7182",
  markupCode: "#765A35",
  regex: "#8D5A68",
  tagBracket: "#877394",
  attributeValue: "#765A35",
};

const pointerPaladinTokens: TokenPalette = {
  bg: "#1E1F33",
  fg: "#FFFFFF",
  comment: "#707E92",
  keyword: "#80F077",
  operator: "#40B488",
  string: "#D6E6FF",
  escape: "#80F077",
  number: "#40B488",
  constant: "#80F077",
  type: "#B8FFE0",
  function: "#FFFFFF",
  parameter: "#D6E6FF",
  property: "#FFFFFF",
  tag: "#80F077",
  attribute: "#40B488",
  delimiter: "#A5B3C8",
  invalid: "#FF7A90",
  inserted: "#80F077",
  deleted: "#FF7A90",
  selection: "#40B48840",
  inactiveSelection: "#707E9238",
  lineHighlight: "#25283D",
  lineNumber: "#707E92",
  activeLineNumber: "#80F077",
  cursor: "#80F077",
  indent: "#30384D",
  activeIndent: "#40B488",
  whitespace: "#30384D",
  widgetBg: "#25283D",
  widgetBorder: "#707E92",
  suggestSelected: "#30384D",
  ghost: "#9EACBF",
  ghostBg: "#40B48818",
  find: "#80F07738",
  findHighlight: "#40B48828",
  decorator: "#B8FFE0",
  macro: "#80F077",
  namespace: "#B8FFE0",
  module: "#D6E6FF",
  label: "#FFFFFF",
  selector: "#40B488",
  configKey: "#40B488",
  configValue: "#D6E6FF",
  configSection: "#B8FFE0",
  markupHeading: "#B8FFE0",
  markupLink: "#80F077",
  markupQuote: "#707E92",
  markupCode: "#D6E6FF",
  regex: "#C7B9FF",
  tagBracket: "#40B488",
  attributeValue: "#D6E6FF",
};

const pointerDesertSageTokens: TokenPalette = {
  bg: "#3B342E",
  fg: "#F4E6C8",
  comment: "#A79B86",
  keyword: "#D77C56",
  operator: "#B8B08C",
  string: "#DCC9A1",
  escape: "#D77C56",
  number: "#AFC198",
  constant: "#AFC198",
  type: "#D9CFAD",
  function: "#E6B874",
  parameter: "#DCC9A1",
  property: "#F4E6C8",
  tag: "#D77C56",
  attribute: "#AFC198",
  delimiter: "#B8B08C",
  invalid: "#E07E5B",
  inserted: "#AFC198",
  deleted: "#D77C56",
  selection: "#7F8A694A",
  inactiveSelection: "#B8B08C24",
  lineHighlight: "#443D35",
  lineNumber: "#A79B86",
  activeLineNumber: "#DCC9A1",
  cursor: "#DCC9A1",
  indent: "#534A40",
  activeIndent: "#7F8A69",
  whitespace: "#534A40",
  widgetBg: "#443D35",
  widgetBorder: "#7F8A69",
  suggestSelected: "#534A40",
  ghost: "#B8B08C",
  ghostBg: "#7F8A6918",
  find: "#DCC9A13A",
  findHighlight: "#B8B08C28",
  decorator: "#E6B874",
  macro: "#D77C56",
  namespace: "#D9CFAD",
  module: "#DCC9A1",
  label: "#E6B874",
  selector: "#AFC198",
  configKey: "#AFC198",
  configValue: "#DCC9A1",
  configSection: "#D9CFAD",
  markupHeading: "#D9CFAD",
  markupLink: "#E6B874",
  markupQuote: "#A79B86",
  markupCode: "#DCC9A1",
  regex: "#C99A75",
  tagBracket: "#B8B08C",
  attributeValue: "#DCC9A1",
};

const pointerSalmonTokens: TokenPalette = {
  bg: "#041F1E",
  fg: "#F7DBA7",
  comment: "#8CA39B",
  keyword: "#F1AB86",
  operator: "#C57B57",
  string: "#F7DBA7",
  escape: "#F1AB86",
  number: "#DFA06F",
  constant: "#DFA06F",
  type: "#A7C9BD",
  function: "#C57B57",
  parameter: "#F1AB86",
  property: "#F7DBA7",
  tag: "#F1AB86",
  attribute: "#DFA06F",
  delimiter: "#B68F75",
  invalid: "#FF8A77",
  inserted: "#F7DBA7",
  deleted: "#FF8A77",
  selection: "#F1AB8638",
  inactiveSelection: "#C57B5728",
  lineHighlight: "#0A2928",
  lineNumber: "#7F9790",
  activeLineNumber: "#F1AB86",
  cursor: "#F7DBA7",
  indent: "#1E2D2F",
  activeIndent: "#C57B57",
  whitespace: "#1E2D2F",
  widgetBg: "#0A2928",
  widgetBorder: "#1E2D2F",
  suggestSelected: "#153333",
  ghost: "#A8B8AF",
  ghostBg: "#F1AB8614",
  find: "#F7DBA73A",
  findHighlight: "#F1AB8628",
  decorator: "#A7C9BD",
  macro: "#F1AB86",
  namespace: "#A7C9BD",
  module: "#F7DBA7",
  label: "#C57B57",
  selector: "#DFA06F",
  configKey: "#DFA06F",
  configValue: "#F7DBA7",
  configSection: "#A7C9BD",
  markupHeading: "#A7C9BD",
  markupLink: "#F1AB86",
  markupQuote: "#8CA39B",
  markupCode: "#F7DBA7",
  regex: "#F0C0A0",
  tagBracket: "#C57B57",
  attributeValue: "#F7DBA7",
};

const pointerDarkPhotonTokens: TokenPalette = {
  bg: "#282C34",
  fg: "#ABB2BF",
  comment: "#7D8799",
  keyword: "#C678DD",
  operator: "#56B6C2",
  string: "#98C379",
  escape: "#56B6C2",
  number: "#D19A66",
  constant: "#D19A66",
  type: "#E5C07B",
  function: "#61AFEF",
  parameter: "#E06C75",
  property: "#E06C75",
  tag: "#E06C75",
  attribute: "#D19A66",
  delimiter: "#ABB2BF",
  invalid: "#FFFFFF",
  inserted: "#98C379",
  deleted: "#E06C75",
  selection: "#3E4451",
  inactiveSelection: "#3E445188",
  lineHighlight: "#2C313A",
  lineNumber: "#5C6370",
  activeLineNumber: "#ABB2BF",
  cursor: "#528BFF",
  indent: "#3B4048",
  activeIndent: "#636D83",
  whitespace: "#3B4048",
  widgetBg: "#353A42",
  widgetBorder: "#3E4451",
  suggestSelected: "#2C313A",
  ghost: "#7D8799",
  ghostBg: "#528BFF14",
  find: "#528BFF33",
  findHighlight: "#528BFF22",
};

const pointerHarmonicTideTokens: TokenPalette = {
  bg: "#262335",
  fg: "#FFFFFF",
  comment: "#495495",
  keyword: "#FF7EDB",
  operator: "#72F1B8",
  string: "#72F1B8",
  escape: "#FF6AD5",
  number: "#F97E72",
  constant: "#F97E72",
  type: "#FEDE5D",
  function: "#36F9F6",
  parameter: "#F97E72",
  property: "#36F9F6",
  tag: "#FF7EDB",
  attribute: "#FEDE5D",
  delimiter: "#848BBD",
  invalid: "#FE4450",
  inserted: "#72F1B8",
  deleted: "#FE4450",
  selection: "#34294F",
  inactiveSelection: "#34294F88",
  lineHighlight: "#2A2139",
  lineNumber: "#848BBD",
  activeLineNumber: "#FF7EDB",
  cursor: "#FF7EDB",
  indent: "#34294F",
  activeIndent: "#495495",
  whitespace: "#34294F",
  widgetBg: "#2A2139",
  widgetBorder: "#495495",
  suggestSelected: "#34294F",
  ghost: "#B893CE",
  ghostBg: "#FF7EDB14",
  find: "#FEDE5D44",
  findHighlight: "#FEDE5D28",
};

const pointerRocketTokens: TokenPalette = {
  bg: "#212121",
  fg: "#DEDFE4",
  comment: "#707070",
  keyword: "#F07178",
  operator: "#89DDFF",
  string: "#C3E88D",
  escape: "#FFCB6B",
  number: "#F78C6C",
  constant: "#F78C6C",
  type: "#FFCB6B",
  function: "#82AAFF",
  parameter: "#F78C6C",
  property: "#DEDFE4",
  tag: "#F07178",
  attribute: "#FFCB6B",
  delimiter: "#89DDFF",
  invalid: "#D46C6C",
  inserted: "#C3E88D",
  deleted: "#F07178",
  selection: "#333333",
  inactiveSelection: "#33333388",
  lineHighlight: "#333333",
  lineNumber: "#858585",
  activeLineNumber: "#B0B0B0",
  cursor: "#FFCC00",
  indent: "#333333",
  activeIndent: "#4A4A4A",
  whitespace: "#333333",
  widgetBg: "#292929",
  widgetBorder: "#3A3A3A",
  suggestSelected: "#333333",
  ghost: "#858585",
  ghostBg: "#80CBC414",
  find: "#80CBC444",
  findHighlight: "#80CBC428",
};

const pointerMeteorTokens: TokenPalette = {
  bg: "#212121",
  fg: "#C4C4C4",
  comment: "#888888",
  keyword: "#F47078",
  operator: "#88DCFF",
  string: "#80C880",
  escape: "#FFCC64",
  number: "#F88C68",
  constant: "#F88C68",
  type: "#FFCC64",
  function: "#60B4F8",
  parameter: "#F88C68",
  property: "#C4C4C4",
  tag: "#F47078",
  attribute: "#FFCC64",
  delimiter: "#88DCFF",
  invalid: "#F47078",
  inserted: "#80C880",
  deleted: "#F47078",
  selection: "#373737",
  inactiveSelection: "#34343488",
  lineHighlight: "#373737",
  lineNumber: "#888888",
  activeLineNumber: "#C4C4C4",
  cursor: "#FFCC64",
  indent: "#343434",
  activeIndent: "#4A4A4A",
  whitespace: "#303030",
  widgetBg: "#212121",
  widgetBorder: "#343434",
  suggestSelected: "#343434",
  ghost: "#888888",
  ghostBg: "#80CBC414",
  find: "#80CBC444",
  findHighlight: "#80CBC428",
};

const pointerDarkColaTokens: TokenPalette = {
  bg: "#2B2B2B",
  fg: "#A9B7C6",
  comment: "#808080",
  keyword: "#CC7832",
  operator: "#A9B7C6",
  string: "#6A8759",
  escape: "#CC7832",
  number: "#6897BB",
  constant: "#6897BB",
  type: "#A9B7C6",
  function: "#FFC66D",
  parameter: "#A9B7C6",
  property: "#A9B7C6",
  tag: "#E8BF6A",
  attribute: "#BABABA",
  delimiter: "#A9B7C6",
  invalid: "#BC3F3C",
  inserted: "#6A8759",
  deleted: "#BC3F3C",
  selection: "#214283",
  inactiveSelection: "#21428388",
  lineHighlight: "#323232",
  lineNumber: "#606366",
  activeLineNumber: "#A9B7C6",
  cursor: "#BBBBBB",
  indent: "#3C3F41",
  activeIndent: "#606366",
  whitespace: "#3C3F41",
  widgetBg: "#3C3F41",
  widgetBorder: "#555555",
  suggestSelected: "#4B6EAF",
  ghost: "#808080",
  ghostBg: "#3C3F4188",
  find: "#32593D",
  findHighlight: "#32593D99",
};

const pointerVampireTokens: TokenPalette = {
  bg: "#282A36",
  fg: "#F8F8F2",
  comment: "#6272A4",
  keyword: "#FF79C6",
  operator: "#FF79C6",
  string: "#F1FA8C",
  escape: "#FFB86C",
  number: "#BD93F9",
  constant: "#BD93F9",
  type: "#8BE9FD",
  function: "#50FA7B",
  parameter: "#FFB86C",
  property: "#F8F8F2",
  tag: "#FF79C6",
  attribute: "#50FA7B",
  delimiter: "#F8F8F2",
  invalid: "#FF5555",
  inserted: "#50FA7B",
  deleted: "#FF5555",
  selection: "#44475A",
  inactiveSelection: "#44475A99",
  lineHighlight: "#44475A55",
  lineNumber: "#6272A4",
  activeLineNumber: "#F8F8F2",
  cursor: "#F8F8F0",
  indent: "#44475A",
  activeIndent: "#6272A4",
  whitespace: "#44475A",
  widgetBg: "#282A36",
  widgetBorder: "#44475A",
  suggestSelected: "#44475A",
  ghost: "#A7B0D6",
  ghostBg: "#44475A66",
  find: "#FFB86C55",
  findHighlight: "#FFB86C33",
};

const pointerMonkeyProTokens: TokenPalette = {
  bg: "#2D2A2E",
  fg: "#FCFCFA",
  comment: "#727072",
  keyword: "#FF6188",
  operator: "#FF6188",
  string: "#FFD866",
  escape: "#FC9867",
  number: "#AB9DF2",
  constant: "#AB9DF2",
  type: "#78DCE8",
  function: "#A9DC76",
  parameter: "#FC9867",
  property: "#FCFCFA",
  tag: "#FF6188",
  attribute: "#A9DC76",
  delimiter: "#939293",
  invalid: "#FF6188",
  inserted: "#A9DC76",
  deleted: "#FF6188",
  selection: "#403E41",
  inactiveSelection: "#403E4188",
  lineHighlight: "#363438",
  lineNumber: "#727072",
  activeLineNumber: "#FCFCFA",
  cursor: "#FCFCFA",
  indent: "#403E41",
  activeIndent: "#5B595C",
  whitespace: "#403E41",
  widgetBg: "#363438",
  widgetBorder: "#5B595C",
  suggestSelected: "#403E41",
  ghost: "#939293",
  ghostBg: "#403E4166",
  find: "#FFD86644",
  findHighlight: "#FFD86626",
};

export const POINTER_THEMES: PointerTheme[] = [
  createTheme({
    id: "pointer-noir",
    label: "Pointer Noir",
    type: "dark",
    css: {
      "--pn-canvas": "#08070B",
      "--pn-panel": "#0E0C10",
      "--pn-chrome": "#15121A",
      "--pn-ridge": "#211722",
      "--pn-line": "#432238",
      "--pn-text": "#F2EDF5",
      "--pn-subtext": "#C7BBCB",
      "--pn-mute": "#8D7F8B",
      "--pn-accent": "#FF2D7E",
      "--pn-accent-hot": "#FF4F9A",
      "--pn-accent-soft": "#FF9AC3",
      "--pn-accent-deep": "#8B164A",
      "--pn-cyan": "#78D8FF",
      "--pn-ok": "#7CE8B7",
      "--pn-warn": "#FFD37A",
      "--pn-err": "#FF5C86",
      "--pn-body-bg": "#050407",
      "--pn-titlebar-bg": "rgba(12, 9, 13, 0.97)",
      "--pn-app-shell-bg": "#070509",
      "--pn-app-shell-highlight": "rgba(255, 45, 126, 0.055)",
      "--pn-glass-bg": "rgba(14, 12, 16, 0.96)",
      "--pn-panel-top": "rgba(18, 14, 20, 0.96)",
      "--pn-panel-bottom": "rgba(10, 8, 13, 0.98)",
      "--pn-soft-top": "rgba(23, 18, 25, 0.93)",
      "--pn-soft-bottom": "rgba(12, 9, 14, 0.96)",
      "--pn-scrollbar-thumb": "#372031",
      "--pn-scrollbar-thumb-hover": "#52304A",
      "--pn-inset-highlight": "rgba(255, 45, 126, 0.09)",
    },
    tokens: pointerNoirTokens,
  }),
  createTheme({
    id: "pointer-gris",
    label: "Pointer Gris",
    type: "dark",
    css: {
      "--pn-canvas": "#302E33",
      "--pn-panel": "#38353B",
      "--pn-chrome": "#413D45",
      "--pn-ridge": "#4C4650",
      "--pn-line": "#6E5868",
      "--pn-text": "#F2EEF3",
      "--pn-subtext": "#D3C8D1",
      "--pn-mute": "#A99BA6",
      "--pn-accent": "#FF6EA8",
      "--pn-accent-hot": "#FF82B7",
      "--pn-accent-soft": "#FFC7DD",
      "--pn-accent-deep": "#B02B6A",
      "--pn-cyan": "#91DDF6",
      "--pn-ok": "#92E4B6",
      "--pn-warn": "#FFD27A",
      "--pn-err": "#FF6B8B",
      "--pn-body-bg": "#27252A",
      "--pn-titlebar-bg": "rgba(56, 53, 59, 0.97)",
      "--pn-app-shell-bg": "#302E33",
      "--pn-app-shell-highlight": "rgba(255, 110, 168, 0.06)",
      "--pn-glass-bg": "rgba(56, 53, 59, 0.96)",
      "--pn-panel-top": "rgba(67, 62, 70, 0.94)",
      "--pn-panel-bottom": "rgba(48, 46, 51, 0.96)",
      "--pn-soft-top": "rgba(73, 68, 76, 0.9)",
      "--pn-soft-bottom": "rgba(56, 53, 59, 0.94)",
      "--pn-scrollbar-thumb": "#5C5059",
      "--pn-scrollbar-thumb-hover": "#756370",
      "--pn-inset-highlight": "rgba(255, 110, 168, 0.08)",
    },
    tokens: pointerGrisTokens,
  }),
  createTheme({
    id: "pointer-blanc",
    label: "Pointer Blanc",
    type: "light",
    css: {
      "--pn-canvas": "#FAF7FA",
      "--pn-panel": "#FFFCFE",
      "--pn-chrome": "#F0EAF0",
      "--pn-ridge": "#E8DFE7",
      "--pn-line": "#DAC8D4",
      "--pn-text": "#211A20",
      "--pn-subtext": "#5E4F5B",
      "--pn-mute": "#897986",
      "--pn-accent": "#D92A6E",
      "--pn-accent-hot": "#F0448B",
      "--pn-accent-soft": "#FF9EC7",
      "--pn-accent-deep": "#8F164A",
      "--pn-cyan": "#0B6F8F",
      "--pn-ok": "#19714A",
      "--pn-warn": "#A06A00",
      "--pn-err": "#C52845",
      "--pn-body-bg": "#EFE9EF",
      "--pn-titlebar-bg": "rgba(255, 252, 254, 0.97)",
      "--pn-app-shell-bg": "#F8F4F8",
      "--pn-app-shell-highlight": "rgba(217, 42, 110, 0.06)",
      "--pn-glass-bg": "rgba(255, 252, 254, 0.96)",
      "--pn-panel-top": "rgba(255, 252, 254, 0.96)",
      "--pn-panel-bottom": "rgba(247, 241, 247, 0.98)",
      "--pn-soft-top": "rgba(255, 252, 254, 0.92)",
      "--pn-soft-bottom": "rgba(245, 238, 245, 0.94)",
      "--pn-scrollbar-thumb": "#D8C7D3",
      "--pn-scrollbar-thumb-hover": "#C8B2C1",
      "--pn-inset-highlight": "rgba(217, 42, 110, 0.11)",
    },
    tokens: pointerBlancTokens,
  }),
  createTheme({
    id: "pointer-magnet",
    label: "Pointer Magnet",
    type: "dark",
    css: {
      "--pn-canvas": "#2F3234",
      "--pn-panel": "#373B3D",
      "--pn-chrome": "#424648",
      "--pn-ridge": "#4C5254",
      "--pn-line": "#596164",
      "--pn-text": "#E0FBFC",
      "--pn-subtext": "#C0D4D5",
      "--pn-mute": "#93A0A3",
      "--pn-accent": "#2A9D8F",
      "--pn-accent-hot": "#E9C46A",
      "--pn-accent-soft": "#E0FBFC",
      "--pn-accent-deep": "#264653",
      "--pn-cyan": "#E0FBFC",
      "--pn-ok": "#2A9D8F",
      "--pn-warn": "#E9C46A",
      "--pn-err": "#E76F51",
      "--pn-body-bg": "#272A2C",
      "--pn-titlebar-bg": "rgba(55, 59, 61, 0.97)",
      "--pn-app-shell-bg": "#2F3234",
      "--pn-app-shell-highlight": "rgba(42, 157, 143, 0.06)",
      "--pn-glass-bg": "rgba(55, 59, 61, 0.96)",
      "--pn-panel-top": "rgba(66, 70, 72, 0.94)",
      "--pn-panel-bottom": "rgba(47, 50, 52, 0.97)",
      "--pn-soft-top": "rgba(76, 82, 84, 0.88)",
      "--pn-soft-bottom": "rgba(55, 59, 61, 0.94)",
      "--pn-scrollbar-thumb": "#596164",
      "--pn-scrollbar-thumb-hover": "#2A9D8F",
      "--pn-inset-highlight": "rgba(233, 196, 106, 0.08)",
      "--pn-status-bg": "#264653",
      "--pn-selection-bg": "#3F4446",
    },
    tokens: pointerMagnetTokens,
  }),
  createTheme({
    id: "pointer-alien",
    label: "Pointer Alien",
    type: "dark",
    css: {
      "--pn-canvas": "#000000",
      "--pn-panel": "#050707",
      "--pn-chrome": "#090C0D",
      "--pn-ridge": "#13262C",
      "--pn-line": "#264653",
      "--pn-text": "#E0FBFC",
      "--pn-subtext": "#B9D7DA",
      "--pn-mute": "#7FA1A6",
      "--pn-accent": "#2A9D8F",
      "--pn-accent-hot": "#E76F51",
      "--pn-accent-soft": "#E9C46A",
      "--pn-accent-deep": "#264653",
      "--pn-cyan": "#E0FBFC",
      "--pn-ok": "#2A9D8F",
      "--pn-warn": "#E9C46A",
      "--pn-err": "#E76F51",
      "--pn-body-bg": "#000000",
      "--pn-titlebar-bg": "rgba(0, 0, 0, 0.98)",
      "--pn-app-shell-bg": "#000000",
      "--pn-app-shell-highlight": "rgba(42, 157, 143, 0.06)",
      "--pn-glass-bg": "rgba(5, 7, 7, 0.97)",
      "--pn-panel-top": "rgba(9, 12, 13, 0.96)",
      "--pn-panel-bottom": "rgba(0, 0, 0, 0.98)",
      "--pn-soft-top": "rgba(19, 38, 44, 0.88)",
      "--pn-soft-bottom": "rgba(5, 7, 7, 0.96)",
      "--pn-scrollbar-thumb": "#264653",
      "--pn-scrollbar-thumb-hover": "#2A9D8F",
      "--pn-inset-highlight": "rgba(233, 196, 106, 0.09)",
      "--pn-status-bg": "#264653",
      "--pn-selection-bg": "#102A2E",
    },
    tokens: pointerAlienTokens,
  }),
  createTheme({
    id: "pointer-pastelle",
    label: "Pointer Pastelle",
    type: "light",
    css: {
      "--pn-canvas": "#ECE3C4",
      "--pn-panel": "#F6EED6",
      "--pn-chrome": "#E4D4B8",
      "--pn-ridge": "#CDBBA0",
      "--pn-line": "#CDBBA0",
      "--pn-text": "#332A35",
      "--pn-subtext": "#5C515F",
      "--pn-mute": "#80736D",
      "--pn-accent": "#739A9E",
      "--pn-accent-hot": "#A7424B",
      "--pn-accent-soft": "#EA8A8A",
      "--pn-accent-deep": "#877394",
      "--pn-cyan": "#4E7477",
      "--pn-ok": "#4E7477",
      "--pn-warn": "#996A2F",
      "--pn-err": "#A7424B",
      "--pn-body-bg": "#D9C9AD",
      "--pn-titlebar-bg": "rgba(246, 238, 214, 0.97)",
      "--pn-app-shell-bg": "#ECE3C4",
      "--pn-app-shell-highlight": "rgba(234, 138, 138, 0.12)",
      "--pn-glass-bg": "rgba(246, 238, 214, 0.96)",
      "--pn-panel-top": "rgba(246, 238, 214, 0.96)",
      "--pn-panel-bottom": "rgba(236, 227, 196, 0.98)",
      "--pn-soft-top": "rgba(228, 212, 184, 0.92)",
      "--pn-soft-bottom": "rgba(236, 227, 196, 0.96)",
      "--pn-scrollbar-thumb": "#CDBBA0",
      "--pn-scrollbar-thumb-hover": "#739A9E",
      "--pn-inset-highlight": "rgba(135, 115, 148, 0.11)",
      "--pn-status-bg": "#877394",
      "--pn-selection-bg": "#EA8A8A55",
    },
    tokens: pointerPastelleTokens,
  }),
  createTheme({
    id: "pointer-paladin",
    label: "Pointer Paladin",
    type: "dark",
    css: {
      "--pn-canvas": "#1E1F33",
      "--pn-panel": "#25283D",
      "--pn-chrome": "#2B3148",
      "--pn-ridge": "#30384D",
      "--pn-line": "#707E92",
      "--pn-text": "#FFFFFF",
      "--pn-subtext": "#D6E6FF",
      "--pn-mute": "#9EACBF",
      "--pn-accent": "#40B488",
      "--pn-accent-hot": "#80F077",
      "--pn-accent-soft": "#FFFFFF",
      "--pn-accent-deep": "#1E1F33",
      "--pn-cyan": "#B8FFE0",
      "--pn-ok": "#80F077",
      "--pn-warn": "#D6E6FF",
      "--pn-err": "#FF7A90",
      "--pn-body-bg": "#151629",
      "--pn-titlebar-bg": "rgba(30, 31, 51, 0.98)",
      "--pn-app-shell-bg": "#1E1F33",
      "--pn-app-shell-highlight": "rgba(128, 240, 119, 0.06)",
      "--pn-glass-bg": "rgba(37, 40, 61, 0.97)",
      "--pn-panel-top": "rgba(43, 49, 72, 0.95)",
      "--pn-panel-bottom": "rgba(30, 31, 51, 0.98)",
      "--pn-soft-top": "rgba(48, 56, 77, 0.9)",
      "--pn-soft-bottom": "rgba(37, 40, 61, 0.95)",
      "--pn-scrollbar-thumb": "#707E92",
      "--pn-scrollbar-thumb-hover": "#40B488",
      "--pn-inset-highlight": "rgba(128, 240, 119, 0.09)",
      "--pn-status-bg": "#1E1F33",
      "--pn-selection-bg": "#40B48840",
    },
    tokens: pointerPaladinTokens,
  }),
  createTheme({
    id: "pointer-desert-sage",
    label: "Pointer Desert Sage",
    type: "dark",
    css: {
      "--pn-canvas": "#3B342E",
      "--pn-panel": "#443D35",
      "--pn-chrome": "#4B433A",
      "--pn-ridge": "#534A40",
      "--pn-line": "#7F8A69",
      "--pn-text": "#F4E6C8",
      "--pn-subtext": "#DCC9A1",
      "--pn-mute": "#A79B86",
      "--pn-accent": "#7F8A69",
      "--pn-accent-hot": "#D77C56",
      "--pn-accent-soft": "#DCC9A1",
      "--pn-accent-deep": "#3B342E",
      "--pn-cyan": "#AFC198",
      "--pn-ok": "#AFC198",
      "--pn-warn": "#E6B874",
      "--pn-err": "#D77C56",
      "--pn-body-bg": "#2D2824",
      "--pn-titlebar-bg": "rgba(59, 52, 46, 0.98)",
      "--pn-app-shell-bg": "#3B342E",
      "--pn-app-shell-highlight": "rgba(127, 138, 105, 0.07)",
      "--pn-glass-bg": "rgba(68, 61, 53, 0.97)",
      "--pn-panel-top": "rgba(75, 67, 58, 0.95)",
      "--pn-panel-bottom": "rgba(59, 52, 46, 0.98)",
      "--pn-soft-top": "rgba(83, 74, 64, 0.9)",
      "--pn-soft-bottom": "rgba(68, 61, 53, 0.95)",
      "--pn-scrollbar-thumb": "#7F8A69",
      "--pn-scrollbar-thumb-hover": "#B8B08C",
      "--pn-inset-highlight": "rgba(220, 201, 161, 0.09)",
      "--pn-status-bg": "#3B342E",
      "--pn-selection-bg": "#7F8A694A",
    },
    tokens: pointerDesertSageTokens,
  }),
  createTheme({
    id: "pointer-salmon",
    label: "Pointer Salmon",
    type: "dark",
    css: {
      "--pn-canvas": "#041F1E",
      "--pn-panel": "#0A2928",
      "--pn-chrome": "#102A2B",
      "--pn-ridge": "#1E2D2F",
      "--pn-line": "#C57B57",
      "--pn-text": "#F7DBA7",
      "--pn-subtext": "#F1AB86",
      "--pn-mute": "#8CA39B",
      "--pn-accent": "#F1AB86",
      "--pn-accent-hot": "#F7DBA7",
      "--pn-accent-soft": "#C57B57",
      "--pn-accent-deep": "#1E2D2F",
      "--pn-cyan": "#8CA39B",
      "--pn-ok": "#F7DBA7",
      "--pn-warn": "#F1AB86",
      "--pn-err": "#FF8A77",
      "--pn-body-bg": "#031817",
      "--pn-titlebar-bg": "rgba(4, 31, 30, 0.98)",
      "--pn-app-shell-bg": "#041F1E",
      "--pn-app-shell-highlight": "rgba(241, 171, 134, 0.06)",
      "--pn-glass-bg": "rgba(10, 41, 40, 0.97)",
      "--pn-panel-top": "rgba(16, 42, 43, 0.95)",
      "--pn-panel-bottom": "rgba(4, 31, 30, 0.98)",
      "--pn-soft-top": "rgba(30, 45, 47, 0.9)",
      "--pn-soft-bottom": "rgba(10, 41, 40, 0.95)",
      "--pn-scrollbar-thumb": "#1E2D2F",
      "--pn-scrollbar-thumb-hover": "#C57B57",
      "--pn-inset-highlight": "rgba(247, 219, 167, 0.09)",
      "--pn-status-bg": "#041F1E",
      "--pn-selection-bg": "#F1AB8638",
    },
    tokens: pointerSalmonTokens,
  }),
  createTheme({
    id: "pointer-dark-photon",
    label: "Pointer Dark Photon",
    type: "dark",
    css: {
      "--pn-canvas": "#282C34",
      "--pn-panel": "#21252B",
      "--pn-chrome": "#2C313A",
      "--pn-ridge": "#353A42",
      "--pn-line": "#3E4451",
      "--pn-text": "#ABB2BF",
      "--pn-subtext": "#9DA5B4",
      "--pn-mute": "#7D8799",
      "--pn-accent": "#528BFF",
      "--pn-accent-hot": "#61AFEF",
      "--pn-accent-soft": "#56B6C2",
      "--pn-accent-deep": "#2F5FA8",
      "--pn-cyan": "#56B6C2",
      "--pn-ok": "#98C379",
      "--pn-warn": "#E5C07B",
      "--pn-err": "#E06C75",
      "--pn-body-bg": "#1E2227",
      "--pn-titlebar-bg": "rgba(33, 37, 43, 0.97)",
      "--pn-app-shell-bg": "#282C34",
      "--pn-app-shell-highlight": "rgba(82, 139, 255, 0.055)",
      "--pn-glass-bg": "rgba(33, 37, 43, 0.96)",
      "--pn-panel-top": "rgba(44, 49, 58, 0.94)",
      "--pn-panel-bottom": "rgba(33, 37, 43, 0.96)",
      "--pn-soft-top": "rgba(53, 58, 66, 0.9)",
      "--pn-soft-bottom": "rgba(33, 37, 43, 0.94)",
      "--pn-scrollbar-thumb": "#3E4451",
      "--pn-scrollbar-thumb-hover": "#5C6370",
      "--pn-inset-highlight": "rgba(82, 139, 255, 0.08)",
    },
    tokens: pointerDarkPhotonTokens,
  }),
  createTheme({
    id: "pointer-harmonic-tide",
    label: "Pointer Harmonic Tide",
    type: "dark",
    css: {
      "--pn-canvas": "#262335",
      "--pn-panel": "#241B2F",
      "--pn-chrome": "#2A2139",
      "--pn-ridge": "#34294F",
      "--pn-line": "#495495",
      "--pn-text": "#FFFFFF",
      "--pn-subtext": "#D9CBFF",
      "--pn-mute": "#848BBD",
      "--pn-accent": "#FF7EDB",
      "--pn-accent-hot": "#FF6AD5",
      "--pn-accent-soft": "#36F9F6",
      "--pn-accent-deep": "#B893CE",
      "--pn-cyan": "#36F9F6",
      "--pn-ok": "#72F1B8",
      "--pn-warn": "#FEDE5D",
      "--pn-err": "#FE4450",
      "--pn-body-bg": "#1F172A",
      "--pn-titlebar-bg": "rgba(36, 27, 47, 0.97)",
      "--pn-app-shell-bg": "#262335",
      "--pn-app-shell-highlight": "rgba(255, 126, 219, 0.07)",
      "--pn-glass-bg": "rgba(36, 27, 47, 0.96)",
      "--pn-panel-top": "rgba(42, 33, 57, 0.94)",
      "--pn-panel-bottom": "rgba(36, 27, 47, 0.96)",
      "--pn-soft-top": "rgba(52, 41, 79, 0.9)",
      "--pn-soft-bottom": "rgba(36, 27, 47, 0.94)",
      "--pn-scrollbar-thumb": "#34294F",
      "--pn-scrollbar-thumb-hover": "#495495",
      "--pn-inset-highlight": "rgba(255, 126, 219, 0.1)",
    },
    tokens: pointerHarmonicTideTokens,
  }),
  createTheme({
    id: "pointer-rocket",
    label: "Pointer Rocket",
    type: "dark",
    css: {
      "--pn-canvas": "#212121",
      "--pn-panel": "#1E1E1E",
      "--pn-chrome": "#262626",
      "--pn-ridge": "#333333",
      "--pn-line": "#3A3A3A",
      "--pn-text": "#DEDFE4",
      "--pn-subtext": "#B9C0C7",
      "--pn-mute": "#858585",
      "--pn-accent": "#80CBC4",
      "--pn-accent-hot": "#89DDFF",
      "--pn-accent-soft": "#A7FFF6",
      "--pn-accent-deep": "#4F8E89",
      "--pn-cyan": "#89DDFF",
      "--pn-ok": "#C3E88D",
      "--pn-warn": "#FFCB6B",
      "--pn-err": "#F07178",
      "--pn-body-bg": "#1A1A1A",
      "--pn-titlebar-bg": "rgba(30, 30, 30, 0.97)",
      "--pn-app-shell-bg": "#212121",
      "--pn-app-shell-highlight": "rgba(128, 203, 196, 0.055)",
      "--pn-glass-bg": "rgba(30, 30, 30, 0.96)",
      "--pn-panel-top": "rgba(38, 38, 38, 0.94)",
      "--pn-panel-bottom": "rgba(30, 30, 30, 0.96)",
      "--pn-soft-top": "rgba(51, 51, 51, 0.9)",
      "--pn-soft-bottom": "rgba(30, 30, 30, 0.94)",
      "--pn-scrollbar-thumb": "#506C7A",
      "--pn-scrollbar-thumb-hover": "#80CBC4",
      "--pn-inset-highlight": "rgba(128, 203, 196, 0.08)",
    },
    tokens: pointerRocketTokens,
  }),
  createTheme({
    id: "pointer-meteor",
    label: "Pointer Meteor",
    type: "dark",
    css: {
      "--pn-canvas": "#212121",
      "--pn-panel": "#1E1E1E",
      "--pn-chrome": "#1E1E1E",
      "--pn-ridge": "#343434",
      "--pn-line": "#2C2C2C",
      "--pn-text": "#C4C4C4",
      "--pn-subtext": "#A4A4A4",
      "--pn-mute": "#888888",
      "--pn-accent": "#80CBC4",
      "--pn-accent-hot": "#8FE6DD",
      "--pn-accent-soft": "#A7FFF6",
      "--pn-accent-deep": "#4F8E89",
      "--pn-cyan": "#88DCFF",
      "--pn-ok": "#80C880",
      "--pn-warn": "#FFCC64",
      "--pn-err": "#F47078",
      "--pn-body-bg": "#64B898",
      "--pn-titlebar-bg": "rgba(30, 30, 30, 0.98)",
      "--pn-app-shell-bg": "#1E1E1E",
      "--pn-app-shell-highlight": "rgba(128, 203, 196, 0.018)",
      "--pn-glass-bg": "rgba(30, 30, 30, 0.97)",
      "--pn-panel-top": "rgba(30, 30, 30, 0.98)",
      "--pn-panel-bottom": "rgba(30, 30, 30, 0.98)",
      "--pn-soft-top": "rgba(33, 33, 33, 0.96)",
      "--pn-soft-bottom": "rgba(30, 30, 30, 0.98)",
      "--pn-scrollbar-thumb": "#48616D",
      "--pn-scrollbar-thumb-hover": "#80CBC4",
      "--pn-inset-highlight": "rgba(128, 203, 196, 0.04)",
      "--pn-status-bg": "#49616D",
      "--pn-selection-bg": "#343434",
    },
    tokens: pointerMeteorTokens,
  }),
  createTheme({
    id: "pointer-dark-cola",
    label: "Pointer Dark Cola",
    type: "dark",
    css: {
      "--pn-canvas": "#2B2B2B",
      "--pn-panel": "#313335",
      "--pn-chrome": "#3C3F41",
      "--pn-ridge": "#3A3A3A",
      "--pn-line": "#555555",
      "--pn-text": "#A9B7C6",
      "--pn-subtext": "#87939A",
      "--pn-mute": "#6F777D",
      "--pn-accent": "#CC7832",
      "--pn-accent-hot": "#FFC66D",
      "--pn-accent-soft": "#E8BF6A",
      "--pn-accent-deep": "#8C4F1E",
      "--pn-cyan": "#6897BB",
      "--pn-ok": "#6A8759",
      "--pn-warn": "#BBB529",
      "--pn-err": "#BC3F3C",
      "--pn-body-bg": "#242424",
      "--pn-titlebar-bg": "rgba(49, 51, 53, 0.96)",
      "--pn-app-shell-bg": "#2B2B2B",
      "--pn-app-shell-highlight": "rgba(204, 120, 50, 0.05)",
      "--pn-glass-bg": "rgba(49, 51, 53, 0.96)",
      "--pn-panel-top": "rgba(56, 58, 60, 0.94)",
      "--pn-panel-bottom": "rgba(43, 43, 43, 0.96)",
      "--pn-soft-top": "rgba(58, 58, 58, 0.92)",
      "--pn-soft-bottom": "rgba(43, 43, 43, 0.94)",
      "--pn-scrollbar-thumb": "#555555",
      "--pn-scrollbar-thumb-hover": "#666666",
      "--pn-inset-highlight": "rgba(204, 120, 50, 0.08)",
    },
    tokens: pointerDarkColaTokens,
  }),
  createTheme({
    id: "pointer-vampire",
    label: "Pointer Vampire",
    type: "dark",
    css: {
      "--pn-canvas": "#282A36",
      "--pn-panel": "#21222C",
      "--pn-chrome": "#343746",
      "--pn-ridge": "#44475A",
      "--pn-line": "#44475A",
      "--pn-text": "#F8F8F2",
      "--pn-subtext": "#C7C9DD",
      "--pn-mute": "#6272A4",
      "--pn-accent": "#FF79C6",
      "--pn-accent-hot": "#FF92D0",
      "--pn-accent-soft": "#BD93F9",
      "--pn-accent-deep": "#7E4AA8",
      "--pn-cyan": "#8BE9FD",
      "--pn-ok": "#50FA7B",
      "--pn-warn": "#F1FA8C",
      "--pn-err": "#FF5555",
      "--pn-body-bg": "#191A21",
      "--pn-titlebar-bg": "rgba(33, 34, 44, 0.96)",
      "--pn-app-shell-bg": "#282A36",
      "--pn-app-shell-highlight": "rgba(255, 121, 198, 0.06)",
      "--pn-glass-bg": "rgba(33, 34, 44, 0.96)",
      "--pn-panel-top": "rgba(52, 55, 70, 0.92)",
      "--pn-panel-bottom": "rgba(33, 34, 44, 0.96)",
      "--pn-soft-top": "rgba(52, 55, 70, 0.88)",
      "--pn-soft-bottom": "rgba(33, 34, 44, 0.94)",
      "--pn-scrollbar-thumb": "#44475A",
      "--pn-scrollbar-thumb-hover": "#6272A4",
      "--pn-inset-highlight": "rgba(255, 121, 198, 0.09)",
    },
    tokens: pointerVampireTokens,
  }),
  createTheme({
    id: "pointer-monkey-pro",
    label: "Pointer Monkey Pro",
    type: "dark",
    css: {
      "--pn-canvas": "#2D2A2E",
      "--pn-panel": "#363438",
      "--pn-chrome": "#403E41",
      "--pn-ridge": "#403E41",
      "--pn-line": "#5B595C",
      "--pn-text": "#FCFCFA",
      "--pn-subtext": "#C1C0C0",
      "--pn-mute": "#939293",
      "--pn-accent": "#FF6188",
      "--pn-accent-hot": "#FF7D9E",
      "--pn-accent-soft": "#AB9DF2",
      "--pn-accent-deep": "#A83959",
      "--pn-cyan": "#78DCE8",
      "--pn-ok": "#A9DC76",
      "--pn-warn": "#FFD866",
      "--pn-err": "#FF6188",
      "--pn-body-bg": "#221F22",
      "--pn-titlebar-bg": "rgba(54, 52, 56, 0.96)",
      "--pn-app-shell-bg": "#2D2A2E",
      "--pn-app-shell-highlight": "rgba(255, 97, 136, 0.055)",
      "--pn-glass-bg": "rgba(54, 52, 56, 0.96)",
      "--pn-panel-top": "rgba(64, 62, 65, 0.92)",
      "--pn-panel-bottom": "rgba(45, 42, 46, 0.96)",
      "--pn-soft-top": "rgba(64, 62, 65, 0.88)",
      "--pn-soft-bottom": "rgba(45, 42, 46, 0.94)",
      "--pn-scrollbar-thumb": "#5B595C",
      "--pn-scrollbar-thumb-hover": "#727072",
      "--pn-inset-highlight": "rgba(255, 97, 136, 0.08)",
    },
    tokens: pointerMonkeyProTokens,
  }),
];

const THEME_BY_ID = new Map(POINTER_THEMES.map((theme) => [theme.id, theme]));

export const DEFAULT_APP_THEME_ID: AppThemeId = "pointer-noir";

export function isAppThemeId(value: string | null | undefined): value is AppThemeId {
  return POINTER_THEME_IDS.includes(value as AppThemeId);
}

export function normalizeAppThemeId(value: string | null | undefined): AppThemeId {
  if (value === "noir") return "pointer-noir";
  if (value === "light") return "pointer-blanc";
  return isAppThemeId(value) ? value : DEFAULT_APP_THEME_ID;
}

export function pointerThemeFor(value: string | null | undefined): PointerTheme {
  return THEME_BY_ID.get(normalizeAppThemeId(value)) ?? POINTER_THEMES[0];
}

export function applyPointerThemeToDocument(value: string | null | undefined): PointerTheme {
  const theme = pointerThemeFor(value);
  if (typeof document === "undefined") return theme;

  const root = document.documentElement;
  for (const [name, cssValue] of Object.entries(theme.css)) {
    root.style.setProperty(name, cssValue);
    const rgb = hexToRgbTriplet(cssValue);
    if (rgb) root.style.setProperty(`${name}-rgb`, rgb);
    else root.style.removeProperty(`${name}-rgb`);
  }
  root.style.colorScheme = theme.type;
  root.dataset.pointerTheme = theme.id;

  const body = document.body;
  body.dataset.pointerTheme = theme.id;
  body.classList.remove("pn-theme-light", "pn-theme-noir");
  for (const id of POINTER_THEME_IDS) {
    body.classList.toggle(`pn-theme-${id}`, id === theme.id);
  }
  return theme;
}

export function themeActionId(themeId: AppThemeId): `theme:${AppThemeId}` {
  return `theme:${themeId}`;
}
